import Head from "next/head";
import Image from "next/image";
import Mint from "../components/Mint";
import Faq from "../sections/Faq";
import Hero from "../sections/Hero";
import Roadmap from "../sections/Roadmap";
import Team from "../sections/Team";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Cloud Bunnies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="page-container mx-auto overflow-hidden">
        <Hero />
        <Mint />
        <Roadmap />
        <Team />
        <Faq />
      </main>
    </div>
  );
}
